# 라프라시아 프로젝트 - Git Commit & Push
Write-Host "==================================================" -ForegroundColor Cyan
Write-Host "  Git Commit & Push - Lafprasia Project" -ForegroundColor Cyan
Write-Host "==================================================" -ForegroundColor Cyan
Write-Host ""

Set-Location -Path $PSScriptRoot

Write-Host "[1/4] Git 상태 확인 중..." -ForegroundColor Yellow
git status

Write-Host ""
Write-Host "[2/4] 파일 추가 중..." -ForegroundColor Yellow
git add .

Write-Host ""
Write-Host "[3/4] 커밋 중..." -ForegroundColor Yellow
git commit -m "Add complete Lafprasia baseball RPG game system

Features:
- Python game engine with 20+ scenes
- OpenSpec integration (5 AI tools)
- GitHub Actions CI/CD
- Complete documentation
- C# Unity scripts ready

Generated by AI Assistant"

Write-Host ""
Write-Host "[4/4] 푸시 중..." -ForegroundColor Yellow
git push origin main

Write-Host ""
Write-Host "==================================================" -ForegroundColor Green
Write-Host "  완료!" -ForegroundColor Green
Write-Host "==================================================" -ForegroundColor Green
Write-Host ""
Write-Host "GitHub 에서 확인하세요:" -ForegroundColor Cyan
Write-Host "https://github.com/kimjunwoo1206112-oss/Designing-a-Worldview-Simulation-Agent" -ForegroundColor White
Write-Host ""
Write-Host "아무 키나 누르세요..."
$null = $Host.UI.RawUI.ReadKey("NoEcho,IncludeKeyDown")
