@echo off
chcp 65001 > nul
title Git Commit & Push - Lafprasia Project

echo.
echo ╔════════════════════════════════════════════════════════╗
echo ║   Git Commit & Push                                    ║
echo ║   라프라시아 야구 시뮬레이션 RPG                       ║
echo ╚════════════════════════════════════════════════════════╝
echo.

cd /d "%~dp0"

echo [1/4] Git 상태 확인 중...
git status

echo.
echo [2/4] 파일 추가 중...
git add .

echo.
echo [3/4] 커밋 중...
git commit -m "Add complete Lafprasia baseball RPG game system

Features:
- Python game engine with 20+ scenes
- OpenSpec integration (5 AI tools)
- GitHub Actions CI/CD
- Complete documentation
- C# Unity scripts ready

Generated by AI Assistant"

echo.
echo [4/4] 푸시 중...
git push origin main

echo.
echo ╔════════════════════════════════════════════════════════╗
echo ║   완료!                                                ║
echo ╚════════════════════════════════════════════════════════╝
echo.
echo GitHub 에서 확인하세요:
echo https://github.com/kimjunwoo1206112-oss/Designing-a-Worldview-Simulation-Agent
echo.

pause
